### ISSUE TITLE
Tracking issue for misc things

### ISSUE THREAD

**Issue by willcrichton** [scanner-research/scanner#134]
- [ ] Parallel data loading. Takes me 3 hours on 1 box to load 62k shot boundaries!

- [ ] Change .load API. Don't return the indices anymore, just the value. Relatedly, make serializers/deserializers first-class and automatically applied. Introduce a `Serializer` class, don't have separate writers/parsers files.

- [ ] Provide some way of bulk loading VideoDescriptors 

- [ ] Make FORCE_CPU_DECODE a job parameter
