### ISSUE TITLE
Scanner Release Party TODO

### ISSUE THREAD

**Issue by willcrichton** [scanner-research/scanner#148]
**For Will**
- [ ] Re-registering Python ops (#109)
- [ ] Error for creating table w/ same name (#114)
- [ ] Rewrite Github + docs front page
- [ ] Clean up tutorial and walkthrough

**For Alex**
- [ ] Finish source/sinks (#95)
- [ ] Time base info in in-place ingest (#120)
- [ ] Don't materialize gather lists (#126)
- [ ] Fix Halide version (#136)
- [ ] Resolve Python pipeline concurrency issue (#145)
- [ ] Clean up the apps + links to them
