### ISSUE TITLE
Tracking issue for refactor

### ISSUE THREAD

**Issue by willcrichton** [scanner-research/scanner#251]
- [ ] Move all readers/writers into types
- [ ] Add types to C++ ops
- [ ] Rewrite examples/documentation/tutorial
- [ ] Make sure all the error messages are sane

**Comment by willcrichton** [comment]
Moved into interface redesign
